[versions]
kotlin = "2.1.21"
ktfmt = "0.16.0"

telegram = "9.3.0"
chesslib = "1.3.6"
okhttp = "4.12.0"
jackson = "2.16.1"
slf4j = "2.0.9"
logback = "1.4.11"

ktor = "2.3.7"
kotlinx-serialization = "1.6.2"
kotlinx-coroutines = "1.8.0"
junit = "5.10.0"

[libraries]
telegram-bot = { group = "com.github.pengrad", name = "java-telegram-bot-api", version.ref = "telegram" }
chesslib = { group = "com.github.bhlangonijr", name = "chesslib", version.ref = "chesslib" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
jackson-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

ktor-server-core = { group = "io.ktor", name = "ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty-jvm", version.ref = "ktor" }
ktor-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }